►J130. Request for review of task #1
NikolaiShilenko/avalon-dev-j130-laboratornaya-rabota-1 pull request #1
Opened 2021-01-12 21:44 UTC by NikolaiShilenko

@konivex Hello! Here is the solution to task № 1. Please, review and merge it. Thanks!

2021-01-18 21:32 UTC, konivex approved these changes
Зачтено.

2021-01-28 03:29 UTC, NikolaiShilenko commented
@konivex Hello! Here is the solution to task № 2. Please, review it. Thanks!

2021-01-29 04:17 UTC, NikolaiShilenko commented
@konivex Hello! I have solved task № 3. Please, review it. Thanks!

2021-01-30 07:13 UTC, konivex requested changes
Работа 2: Statement-ы и ResultSet-ы не закрыты после использования; надо закрывать(!) и лучше не вызовом .close(), а иначе.
Больше замечаний нет.

Работа 3: зачтено.

2021-01-30 07:52 UTC, NikolaiShilenko commented
@konivex Hello! I have fixed the closing of Statements and ResultSets in class DbServer to task № 3. Please, review it. Thanks!

2021-01-30 08:26 UTC, konivex requested changes
Это не решает проблему. Statement-ы и ResultSet-ы после использования остаются открытыми.

2021-01-30 10:10 UTC, NikolaiShilenko commented
@konivex Hello! I have done it. Please, review it. Thanks!

2021-01-30 10:30 UTC, konivex approved these changes
Зачтено.
Мелкое замечание: когда у вас несколько try-with-resources-блоков, вложенных друг в друга, и их catch-блоки одинаковы (как, например, у вас в методах findDocumentBy*), то catch-блок можно сделать один, прицепленный к самому внешнему try-блоку.

2021-01-30 23:23 UTC, NikolaiShilenko commented
@konivex Hello! I have solved task № 4. I changed the terms of the task. I hope you approve of it.

2021-01-31 14:44 UTC, konivex requested changes
Этот вариант не годится, бесконечный цикл бесполезно расходует процессорное время.

Переделайте на многопоточный вариант, когда на клиенте ввод от пользователя и сообщения от сервера принимаются в разных потоках. Аналогично на сервере, ввод пользователя и сообщения от сервера должны приниматься в разных потоках.

Жду ещё 2-3 дня.

2021-02-01 12:55 UTC, NikolaiShilenko commented
@konivex Hello! I have fixed my project. Please, review it and merge if it's right. Thanks!

2021-02-07 14:30 UTC, konivex requested changes
Обмен по одному сообщению в каждую сторону, да ещё когда к серверу присоединён ровно один клиент — это слишком просто. Сделайте приложение так, чтобы клиент и сервер могли обмениваться фразами до тех пор, пока один из них не завершит работу.

2021-03-27 08:36 UTC, merged